export const products = [
  // Fruits
  {
    productName: "Apple",
    code: "APL001",
    price: 25.0,
    category: "Fruits",
    stock: 100,
    currentStock: 100,
  },
  {
    productName: "Banana",
    code: "BAN002",
    price: 15.0,
    category: "Fruits",
    stock: 200,
    currentStock: 200,
  },
  {
    productName: "Orange",
    code: "ORA003",
    price: 30.0,
    category: "Fruits",
    stock: 150,
    currentStock: 150,
  },
  {
    productName: "Grapes",
    code: "GRP004",
    price: 50.0,
    category: "Fruits",
    stock: 80,
    currentStock: 80,
  },

  // Dairy
  {
    productName: "Milk",
    code: "MLK005",
    price: 60.0,
    category: "Dairy",
    stock: 50,
    currentStock: 50,
  },
  {
    productName: "Eggs",
    code: "EGG006",
    price: 70.0,
    category: "Dairy",
    stock: 60,
    currentStock: 60,
  },
  {
    productName: "Butter",
    code: "BUT007",
    price: 120.0,
    category: "Dairy",
    stock: 40,
    currentStock: 40,
  },
  {
    productName: "Cheddar Cheese",
    code: "CHE008",
    price: 200.0,
    category: "Dairy",
    stock: 30,
    currentStock: 30,
  },
  {
    productName: "Yogurt",
    code: "YOG009",
    price: 50.0,
    category: "Dairy",
    stock: 100,
    currentStock: 100,
  },
  {
    productName: "Mozzarella Cheese",
    code: "MOZ010",
    price: 220.0,
    category: "Dairy",
    stock: 20,
    currentStock: 20,
  },

  // Bakery
  {
    productName: "Bread",
    code: "BRE011",
    price: 35.0,
    category: "Bakery",
    stock: 150,
    currentStock: 150,
  },
  {
    productName: "Wheat Bread",
    code: "WHE013",
    price: 60.0,
    category: "Bakery",
    stock: 100,
    currentStock: 100,
  },
  {
    productName: "Bagel",
    code: "BAG014",
    price: 20.0,
    category: "Bakery",
    stock: 80,
    currentStock: 80,
  },
  {
    productName: "Croissant",
    code: "CRO015",
    price: 25.0,
    category: "Bakery",
    stock: 120,
    currentStock: 120,
  },

  // Grains
  {
    productName: "Rice",
    code: "RIC012",
    price: 40.0,
    category: "Grains",
    stock: 200,
    currentStock: 200,
  },

  // Baking Supplies
  {
    productName: "Sugar",
    code: "SUG016",
    price: 50.0,
    category: "Baking Supplies",
    stock: 150,
    currentStock: 150,
  },
  {
    productName: "Flour",
    code: "FLO017",
    price: 60.0,
    category: "Baking Supplies",
    stock: 130,
    currentStock: 130,
  },
  {
    productName: "Salt",
    code: "SAL018",
    price: 10.0,
    category: "Baking Supplies",
    stock: 200,
    currentStock: 200,
  },
  {
    productName: "Pepper",
    code: "PEP019",
    price: 15.0,
    category: "Baking Supplies",
    stock: 100,
    currentStock: 100,
  },
  {
    productName: "Baking Soda",
    code: "BAK020",
    price: 20.0,
    category: "Baking Supplies",
    stock: 150,
    currentStock: 150,
  },

  // Beverages
  {
    productName: "Coffee",
    code: "COF021",
    price: 100.0,
    category: "Beverages",
    stock: 60,
    currentStock: 60,
  },
  {
    productName: "Coca-Cola 1.5L",
    code: "COC022",
    price: 70.0,
    category: "Beverages",
    stock: 150,
    currentStock: 150,
  },
  {
    productName: "Pepsi 1.5L",
    code: "PEP023",
    price: 65.0,
    category: "Beverages",
    stock: 140,
    currentStock: 140,
  },
  {
    productName: "Nestle Milo",
    code: "NES024",
    price: 70.0,
    category: "Beverages",
    stock: 100,
    currentStock: 100,
  },
  {
    productName: "Energy Drink",
    code: "ENE025",
    price: 90.0,
    category: "Beverages",
    stock: 80,
    currentStock: 80,
  },
  {
    productName: "Instant Coffee",
    code: "INS026",
    price: 180.0,
    category: "Beverages",
    stock: 50,
    currentStock: 50,
  },
  {
    productName: "Green Tea",
    code: "GRE027",
    price: 200.0,
    category: "Beverages",
    stock: 70,
    currentStock: 70,
  },
  {
    productName: "Juice Box",
    code: "JUI028",
    price: 30.0,
    category: "Beverages",
    stock: 200,
    currentStock: 200,
  },
  {
    productName: "Soda Can",
    code: "SOD029",
    price: 25.0,
    category: "Beverages",
    stock: 180,
    currentStock: 180,
  },
  {
    productName: "Bottled Water",
    code: "BOT030",
    price: 15.0,
    category: "Beverages",
    stock: 300,
    currentStock: 300,
  },
  {
    productName: "Sparkling Water",
    code: "SPA031",
    price: 20.0,
    category: "Beverages",
    stock: 100,
    currentStock: 100,
  },

  // Spreads
  {
    productName: "Nutella",
    code: "NUT032",
    price: 250.0,
    category: "Spreads",
    stock: 50,
    currentStock: 50,
  },
  {
    productName: "Honey",
    code: "HON033",
    price: 350.0,
    category: "Spreads",
    stock: 30,
    currentStock: 30,
  },
  {
    productName: "Olive Oil",
    code: "OLI034",
    price: 500.0,
    category: "Spreads",
    stock: 20,
    currentStock: 20,
  },
  {
    productName: "Peanut Butter",
    code: "PEA035",
    price: 250.0,
    category: "Spreads",
    stock: 40,
    currentStock: 40,
  },
  {
    productName: "Cooking Oil",
    code: "COO036",
    price: 120.0,
    category: "Spreads",
    stock: 80,
    currentStock: 80,
  },

  // Snacks
  {
    productName: "Lays Classic",
    code: "LAY037",
    price: 90.0,
    category: "Snacks",
    stock: 150,
    currentStock: 150,
  },
  {
    productName: "Oreo Biscuits",
    code: "ORE038",
    price: 50.0,
    category: "Snacks",
    stock: 100,
    currentStock: 100,
  },
  {
    productName: "KitKat",
    code: "KIT039",
    price: 40.0,
    category: "Snacks",
    stock: 120,
    currentStock: 120,
  },
  {
    productName: "Maggi Noodles",
    code: "MAG040",
    price: 15.0,
    category: "Snacks",
    stock: 200,
    currentStock: 200,
  },
  {
    productName: "Potato Chips",
    code: "POT041",
    price: 60.0,
    category: "Snacks",
    stock: 80,
    currentStock: 80,
  },
  {
    productName: "Cereal Bar",
    code: "CER042",
    price: 50.0,
    category: "Snacks",
    stock: 150,
    currentStock: 150,
  },
  {
    productName: "Chocolates",
    code: "CHO043",
    price: 85.0,
    category: "Snacks",
    stock: 100,
    currentStock: 100,
  },
  {
    productName: "Biscuits",
    code: "BIS044",
    price: 30.0,
    category: "Snacks",
    stock: 180,
    currentStock: 180,
  },
  {
    productName: "Candy Bar",
    code: "CAN045",
    price: 25.0,
    category: "Snacks",
    stock: 200,
    currentStock: 200,
  },
  {
    productName: "Veggie Chips",
    code: "VEG046",
    price: 55.0,
    category: "Snacks",
    stock: 70,
    currentStock: 70,
  },
  {
    productName: "Trail Mix",
    code: "TRA047",
    price: 110.0,
    category: "Snacks",
    stock: 50,
    currentStock: 50,
  },

  // Pantry
  {
    productName: "Pasta",
    code: "PAS048",
    price: 80.0,
    category: "Pantry",
    stock: 100,
    currentStock: 100,
  },
  {
    productName: "Tomato Sauce",
    code: "TOM049",
    price: 35.0,
    category: "Pantry",
    stock: 200,
    currentStock: 200,
  },
  {
    productName: "Corn Flakes",
    code: "COR050",
    price: 150.0,
    category: "Pantry",
    stock: 150,
    currentStock: 150,
  },
  {
    productName: "Pancake Mix",
    code: "PAN051",
    price: 70.0,
    category: "Pantry",
    stock: 50,
    currentStock: 50,
  },
  {
    productName: "Maple Syrup",
    code: "MAP052",
    price: 250.0,
    category: "Pantry",
    stock: 30,
    currentStock: 30,
  },
  {
    productName: "Canned Soup",
    code: "CAN053",
    price: 80.0,
    category: "Pantry",
    stock: 120,
    currentStock: 120,
  },
  {
    productName: "Canned Corn",
    code: "CAN054",
    price: 55.0,
    category: "Pantry",
    stock: 180,
    currentStock: 180,
  },

  // Meat
  {
    productName: "Chicken Breast",
    code: "CHI055",
    price: 220.0,
    category: "Meat",
    stock: 75,
    currentStock: 75,
  },
  {
    productName: "Beef Steak",
    code: "BEE056",
    price: 400.0,
    category: "Meat",
    stock: 50,
    currentStock: 50,
  },
  {
    productName: "Pork Chop",
    code: "POR057",
    price: 320.0,
    category: "Meat",
    stock: 80,
    currentStock: 80,
  },
  {
    productName: "Fish Fillet",
    code: "FIS058",
    price: 250.0,
    category: "Meat",
    stock: 60,
    currentStock: 60,
  },
  {
    productName: "Chicken Nuggets",
    code: "CHI059",
    price: 150.0,
    category: "Meat",
    stock: 100,
    currentStock: 100,
  },

  // Frozen Foods
  {
    productName: "Frozen Pizza",
    code: "FRO060",
    price: 250.0,
    category: "Frozen Foods",
    stock: 40,
    currentStock: 40,
  },
  {
    productName: "Ice Cream Tub",
    code: "ICE061",
    price: 300.0,
    category: "Frozen Foods",
    stock: 20,
    currentStock: 20,
  },
  {
    productName: "Frozen Vegetables",
    code: "FRO062",
    price: 75.0,
    category: "Frozen Foods",
    stock: 150,
    currentStock: 150,
  },
  {
    productName: "Frozen Fries",
    code: "FRO063",
    price: 90.0,
    category: "Frozen Foods",
    stock: 70,
    currentStock: 70,
  },
  {
    productName: "Frozen Dumplings",
    code: "FRO064",
    price: 200.0,
    category: "Frozen Foods",
    stock: 50,
    currentStock: 50,
  },

  // Condiments
  {
    productName: "Ketchup",
    code: "KET065",
    price: 50.0,
    category: "Condiments",
    stock: 300,
    currentStock: 300,
  },
  {
    productName: "Mustard",
    code: "MUS066",
    price: 40.0,
    category: "Condiments",
    stock: 250,
    currentStock: 250,
  },
  {
    productName: "Mayonnaise",
    code: "MAY067",
    price: 60.0,
    category: "Condiments",
    stock: 180,
    currentStock: 180,
  },
  {
    productName: "Soy Sauce",
    code: "SOY068",
    price: 30.0,
    category: "Condiments",
    stock: 400,
    currentStock: 400,
  },

  // Personal Care
  {
    productName: "Shampoo",
    code: "SHA069",
    price: 100.0,
    category: "Personal Care",
    stock: 150,
    currentStock: 150,
  },
  {
    productName: "Toothpaste",
    code: "TOO070",
    price: 50.0,
    category: "Personal Care",
    stock: 200,
    currentStock: 200,
  },
  {
    productName: "Toothbrush",
    code: "TOO071",
    price: 30.0,
    category: "Personal Care",
    stock: 250,
    currentStock: 250,
  },
  {
    productName: "Hand Soap",
    code: "HAN072",
    price: 60.0,
    category: "Personal Care",
    stock: 100,
    currentStock: 100,
  },
  {
    productName: "Face Wash",
    code: "FAC073",
    price: 90.0,
    category: "Personal Care",
    stock: 120,
    currentStock: 120,
  },

  // Ready Meals
  {
    productName: "Shawarma Rice",
    code: "SHA074",
    price: 69.0,
    category: "Ready Meals",
    stock: 80,
    currentStock: 80,
  },

  // Beverages
  {
    productName: "Royal",
    code: "ROY075",
    price: 15.0,
    category: "Beverages",
    stock: 500,
    currentStock: 500,
  },

  // Snacks
  {
    productName: "Twisters",
    code: "TWI076",
    price: 5.0,
    category: "Snacks",
    stock: 600,
    currentStock: 600,
  },
];
