export const productCategories = [
  "All",
  "Fruits",
  "Dairy",
  "Bakery",
  "Grains",
  "Baking Supplies",
  "Beverages",
  "Spreads",
  "Snacks",
  "Pantry",
  "Meat",
  "Frozen Foods",
  "Condiments",
  "Personal Care",
  "Household",
  "Canned Goods",
  "Ready Meals",
];
